services:
  docker-compose-training:
    container_name: docker-compose-training
    depends_on:
      minio:
        condition: service_healthy
    build: .
    ports:
      - 8080:8080
    restart: always

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    container_name: minio
    hostname: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /opt/s3:/var/lib/minio/data
      - /var/log/minio:/var/log/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=qwerty_password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3