env: "local"
minio:
  host: "minio"
  port: "9000"
  access_key: "admin"
  secret_access_key: "qwerty_password"
  ssl_mode: false
  base_bucket: "files.bucket"
  base_path: "./tmp/"

server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 60s
